# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

# stages:
# - test
# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml
stages:
  - test
  - staging
  - production


web-staging:
  image: docker:latest
  stage: staging
  services:
    - docker:dind
  before_script:
    - docker network create scoring_net &> /dev/null || true
  script:
    - docker stop scoring-web &> /dev/null || true
    - docker rm -f scoring-web &> /dev/null || true
    - docker build -f dockerfile-staging -t scoring-web .
  after_script:  
    - docker run --restart always -d -p 3001:3001 --name scoring-web --network=scoring_net --log-opt max-size=20m --log-opt max-file=5 scoring-web
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      exists:
        - dockerfile-staging
  tags:
    - staging

web-production:
  image: docker:latest
  stage: production
  services:
    - docker:dind
  before_script:
    - docker network create scoring_net &> /dev/null || true
  script:
    - docker stop scoring-web &> /dev/null || true
    - docker rm -f scoring-web &> /dev/null || true
    - docker build -f dockerfile-production -t scoring-web .
  after_script:  
    - docker run --restart always -d -p 3001:3001 --name scoring-web --network=scoring_net --log-opt max-size=20m --log-opt max-file=5 scoring-web
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      exists:
        - dockerfile-production
  tags:
    - production