FROM node:20-alpine AS deps
LABEL STG=DEPS
WORKDIR /app
COPY package.json .
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
RUN npm install

FROM node:20-alpine AS builder
LABEL STG=BUILDER
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . ./
COPY public ./public
COPY package.json next.config.js jsconfig.json ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static


ENV PORT 3001

EXPOSE 3001

CMD ["node", "server.js"]