FROM node:18-alpine as base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat

WORKDIR /app
COPY package.json ./
# install dependencies
RUN yarn install --no-lockfile


# Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules 
COPY . .

# build
RUN yarn build

FROM base AS runner
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1

#COPY --from=builder /app/next.config.js ./
#COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static


ENV PORT 3002

EXPOSE 3002

CMD ["node", "server.js"]