import type { Config } from 'tailwindcss'

const config: Config = {
    content: [
        // './src/pages/**/*.{js,ts,jsx,tsx}',
        './src/**/*.{js,ts,jsx,tsx}',
        // './src/components/**/*.{js,ts,jsx,tsx}',
        './src/styles/partials/**/*',
    ],
    darkMode: 'class',
    theme: {
        screens: {
            xs: '480px',
            sm: '640px',
            // => @media (min-width: 640px) { ... }
            md: '768px',
            // => @media (min-width: 768px) { ... }
            lg: '1024px',
            // => @media (min-width: 1024px) { ... }
            xl: '1280px',
            // => @media (min-width: 1280px) { ... }
            '2xl': '1536px',
            '3xl': '1600px',
        },
        container: {
            center: true,
            padding: '0px',
            screens: {
                sm: '640px', // Set max-width for small screens (e.g., mobile)
                md: '768px', // Set max-width for medium screens (e.g., tablet)
                lg: '1024px', // Set max-width for large screens (e.g., laptop)
                xl: '1400px', // Set max-width for extra-large screens (e.g., desktop)
                xxl: '1400px',
            },
        },
        backgroundImage: {
            'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
            'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        },

        fontFamily: {
            abelRegular: ['Abel-Regular', 'sans-serif'],
            tekoLight: ['Teko-Light', 'sans-serif'],
            tekoRegular: ['Teko-Regular', 'sans-serif'],
            tekoMedium: ['Teko-Medium', 'sans-serif'],
            tekoSemiBold: ['Teko-SemiBold', 'sans-serif'],
            tekoBold: ['Teko-Bold', 'sans-serif'],

            notoLight: ['NotoSansKR-Light', 'sans-serif'],
            notoRegular: ['NotoSansKR-Regular', 'sans-serif'],
            notoMedium: ['NotoSansKR-Medium', 'sans-serif'],
            notoSemiBold: ['NotoSansKR-SemiBold', 'sans-serif'],
            notoBold: ['NotoSansKR-Bold', 'sans-serif'],

            robotoLight: ['Roboto-Light', 'sans-serif'],
            robotoRegular: ['Roboto-Regular', 'sans-serif'],
            robotoMedium: ['Roboto-Medium', 'sans-serif'],
            robotoBold: ['Roboto-Bold', 'sans-serif'],

            SignikaLight: ['Signika-Light', 'sans-serif'],
            SignikaRegular: ['Signika-Regular', 'sans-serif'],
            SignikaMedium: ['Signika-Medium', 'sans-serif'],
            SignikaBold: ['Signika-Bold', 'sans-serif'],

            Inter: ['Inter-Regular', 'sans-serif'],

            SignikascRegular: ['Signika-sc-regular', 'sans-serif'],
        },
        fontSize: {
            8: 'var(--font-8)',
            10: 'var(--font-10)',
            12: 'var(--font-12)',
            14: 'var(--font-14)',
            15: 'var(--font-15)',
            16: 'var(--font-16)',
            18: 'var(--font-18)',
            20: 'var(--font-20)',
            22: 'var(--font-22)',
            24: 'var(--font-24)',
            25: 'var(--font-25)',
            26: 'var(--font-26)',
            30: 'var(--font-30)',
            34: 'var(--font-34)',
            35: 'var(--font-35)',
            38: 'var(--font-38)',
            40: 'var(--font-40)',
            50: 'var(--font-50)',
            60: 'var(--font-60)',
            80: 'var(--font-80)',
            100: 'var(--font-100)',
        },
        fontWeight: {
            100: '100',
            200: '200',
            300: '300',
            400: '400',
            500: '500',
            600: '600',
            700: '700',
            800: '800',
        },
        spacing: {
            0: '0',
            1: '1px',
            2: 'var(--space-2)',
            3: 'var(--space-3)',
            4: 'var(--space-4)',
            5: 'var(--space-5)',
            6: 'var(--space-6)',
            7: 'var(--space-7)',
            8: 'var(--space-8)',
            9: 'var(--space-9)',
            10: 'var(--space-10)',
            12: 'var(--space-12)',
            14: 'var(--space-14)',
            15: 'var(--space-15)',
            16: 'var(--space-16)',
            18: 'var(--space-18)',
            20: 'var(--space-20)',
            22: 'var(--space-22)',
            30: 'var(--space-30)',
            36: 'var(--space-36)',
            40: 'var(--space-40)',
            50: 'var(--space-50)',
            60: 'var(--space-60)',
            68: 'var(--space-68)',
            78: 'var(--space-78)',
            80: 'var(--space-80)',
            137: 'var(--space-137)',
            220: 'var(--space-220)',
            283: 'var(--space-283)',
        },
        lineHeight: {
            16: 'var(--font-16)',
            24: 'var(--font-24)',
            26: 'var(--font-26)',
            27: 'var(--font-26)',
            30: 'var(--font-30)',
            35: 'var(--font-34)',
            40: 'var(--font-40)',
            45: '45px',
            50: 'var(--font-50)',
            normal: '1.5',
        },
        letterSpacing: {
            tightest: '-.075em',
            tighter: '-.05em',
            tight: '-.025em',
            normal: '0',
            wide: '.025em',
            wider: '.5px',
            widest: '.1em',
        },
        textIndent: {
            '128': '32rem',
        },

        extend: {
            colors: {
                transparent: 'rgba(255, 255, 255, 0)',
                white: '#fff',
                blue: '#0000ee',
                blueSoft: '#6366f1',
                orange: '#ff7849',
                green: '#13ce66',
                yellow: '#ffc82c',
                purple: '#6821AF',
                lightPurple: '#8B35E2',
                darkPurple: '#8710FF',
                blackPurple: '#463459',
                rebacaPurple: '#5A397A',
                mauve: '#935FFF',
                barPurple: '#6705B3',
                pink: '#CA95FF',
                pinkText: '#9A91C6',
                pinkerbell: '#6E6593',
                pinkTableHead: '#2F2B3F',
                lightPink: '#C6ABFF',
                darkPink: '#CA1C9C',
                darkPopupText: '#27202A',
                black: '#1A191F',
                blackSoft: '#1F1F1F',
                blacklight: '#211E2F',
                blackpink: '#9F8EA7',
                blackRowHover: '#16151B',
                aspalt: '#523F62',
                gray: {
                    40: '#F1F1F1',
                    50: '#BDBDBD',
                    60: '#B7AEB6',
                    70: '#929292',
                    100: '#BEBEBE',
                    300: '#BCBCBC',
                    400: '#D6D6D6',
                    500: '#8B8B8B',
                    550: '#494949',
                    600: '#6B6976',
                    700: '#2D2B3A',
                    800: '#6C6271',
                    900: '#1a202c',
                },
            },
            borderRadius: {
                none: '0',
                sm: '0.125rem',
                DEFAULT: '0.25rem',
                md: '0.375rem',
                lg: '0.5rem',
                full: '9999px',
            },
            borderWidth: {
                DEFAULT: '1px',
                '0': '0',
                '2': '2px',
                '3': '3px',
                '4': '4px',
                '6': '6px',
                '8': '8px',
            },
            gridTemplateColumns: {
                '16': 'repeat(16, minmax(0, 1fr))',
                footer: '200px minmax(900px, 1fr) 100px',
            },

            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
            },
            blur: {
                xs: '2px',
            },
            brightness: {
                25: '.25',
                175: '1.75',
            },
            contrast: {
                25: '.25',
            },
            dropShadow: {
                '3xl': '0 35px 35px rgba(0, 0, 0, 0.25)',
                '4xl': ['0 35px 35px rgba(0, 0, 0, 0.25)', '0 45px 65px rgba(0, 0, 0, 0.15)'],
            },
            grayscale: {
                50: '50%',
            },
            hueRotate: {
                '-270': '-270deg',
                270: '270deg',
            },
            zIndex: {
                '100': '100',
            },
            keyframes: {
                slideDown: {
                    from: { height: '0' },
                    to: { height: '70px' },
                },
                slideUp: {
                    from: { height: '70px' },
                    to: { height: '0' },
                },
                overlayShow: {
                    from: { opacity: '0' },
                    to: { opacity: '1' },
                },
                contentShow: {
                    from: { opacity: '0', transform: 'translate(-50%, -48%) scale(0.96)' },
                    to: { opacity: '1', transform: 'translate(-50%, -50%) scale(1)' },
                },
            },
            animation: {
                slideDown: 'slideDown 300ms cubic-bezier(0.87, 0, 0.13, 1)',
                slideUp: 'slideUp 300ms cubic-bezier(0.87, 0, 0.13, 1)',
                overlayShow: 'overlayShow 150ms cubic-bezier(0.16, 1, 0.3, 1)',
                contentShow: 'contentShow 150ms cubic-bezier(0.16, 1, 0.3, 1)',
            },
        },
    },
    plugins: [require('tailwind-scrollbar-hide')],
}
export default config
