FROM node:19 AS deps
LABEL STG=METAVERSEA_DEPS
WORKDIR /app
COPY package.json .
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
RUN npm install

FROM node:19 AS builder
LABEL STG=METAVERSEA_BUILDER
WORKDIR /app
COPY . ./
COPY --from=deps /app/node_modules ./node_modules
COPY public ./public
COPY package.json next.config.js jsconfig.json ./
RUN npm run build

FROM node:19
WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

CMD ["node", "server.js"]
