version: "3"
services:
  nextjs_server:
    # image: node:18-alpine
    build: ./
    volumes:
      - /home/itw/trust_assurance/upload_cache:/home/cache
    # working_dir: /home
    # command: tail -f /dev/null
    # command: npm run start
    ports:
      - 80:3000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    networks:
      - trust_assurance_net
  nginx_ssl:
    build: ./nginx
    ports:
      - 443:443
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    depends_on:
      - nextjs_server
    networks:
      - trust_assurance_net

networks:
  trust_assurance_net:
    external: true